version: '3.8'
services:
  diagram_db:
    image: postgres:13
    restart: unless-stopped
    container_name: diagram_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: Diagrama
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    environment:
      NODE_ENV: dev
      PORT: 3001
      DATABASE_URL: postgresql://postgres:123@diagram_db/Diagrama?schema=public
      SECRET_KEY_JWT: MILLAVE123
      ACCOUNT_EMAIL: roberthuarachi27@gmail.com
      PASSWORD_EMAIL: bijx toeb ayiy rvcl
      HOST_EMAIL: smtp.gmail.com
      URL_FRONTEND: http://localhost:3000
      OPENAI_API_KEY: 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
      LIVEBLOCKS_SECRET_KEY: sk_dev_HCDOF9VtNNvtlxQJkWp5naCWyq7T78MychUGsBXsKCNM112T5xoQo2fqQb8IOE4z
    ports:
      - "3001:3001"
    depends_on:
      diagram_db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./src/export/templates:/app/src/export/templates
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge